# NOTE THIS FILE IS HAS BEEN DEPRECATED AND REPLACED BY THE TYPESCRIPT DEFINITION (PROJECT.TS)
# The CLI will automatically look for the project.ts as priority, if you want to ensure you
# use the project manifest, please delete project.ts

specVersion: "1.0.0"

name: "harmony-starter"
version: "0.0.1"
runner:
  node:
    name: "@subql/node-ethereum"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: "This project can be use as a starting point for developing your
  new Harmony SubQuery project"
repository: "https://github.com/subquery/ethereum-subql-starter"

schema:
  file: "./schema.graphql"

network:
  # chainId is the EVM Chain ID, for Harmony this is 1666600000
  # https://chainlist.org/chain/1666600000
  chainId: "1666600000"
  # These endpoint(s) should be non-pruned archive nodes
  # We recommend providing more than one endpoint for improved reliability, performance, and uptime
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  # We suggest providing an array of endpoints for increased speed and reliability
  endpoint:
    - https://api.harmony.one
  # Recommended to provide the HTTP endpoint of a full chain dictionary to speed up processing
  # dictionary: "https://api.subquery.network/sq/subquery/harmony-dictionary"

dataSources:
  - kind: ethereum/Runtime # We use ethereum runtime since Harmony is EVM-compatible
    startBlock: 42793429 # This is the block that the contract was deployed on https://explorer.harmony.one/address/0x6983d1e6def3690c4d616b13597a09e6193ea013
    options:
      # Must be a key of assets
      abi: erc20
      address: "0x6983d1e6def3690c4d616b13597a09e6193ea013" # This is the contract address for Wrapped Ether https://explorer.harmony.one/address/0x6983d1e6def3690c4d616b13597a09e6193ea013
    assets:
      erc20:
        file: "./abis/erc20.abi.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleTransaction
          kind: ethereum/TransactionHandler # We use ethereum handlers since Harmony is EVM-compatible
          filter:
            ## The function can either be the function fragment or signature
            # function: '0x095ea7b3'
            # function: '0x7ff36ab500000000000000000000000000000000000000000000000000000000'
            function: approve(address spender, uint256 amount)
        - handler: handleLog
          kind: ethereum/LogHandler # We use ethereum handlers since Harmony is EVM-compatible
          filter:
            topics:
              ## Follows standard log filters https://docs.ethers.io/v5/concepts/events/
              - Transfer(address indexed from, address indexed to, uint256
                amount)
              # address: "0x60781C2586D68229fde47564546784ab3fACA982"
