specVersion: "1.0.0"

name: "base-goerli-starter"
version: "0.0.1"
runner:
  node:
    name: "@subql/node-ethereum"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: "This project can be use as a starting point for developing your new Base Goerli SubQuery project"
repository: "https://github.com/subquery/ethereum-subql-starter"

schema:
  file: "./schema.graphql"

network:
  # chainId is the EVM Chain ID, for Base Goerli this is 84531
  # https://chainlist.org/chain/84531
  chainId: "84531"
  # This endpoint must be a public non-pruned archive node
  # We recommend providing more than one endpoint for improved reliability, performance, and uptime
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  # You can get them from OnFinality for free https://app.onfinality.io
  # https://documentation.onfinality.io/support/the-enhanced-api-service
  endpoint: ["https://goerli.base.org"]
  # Recommended to provide the HTTP endpoint of a full chain dictionary to speed up processing
  # dictionary: "https://api.subquery.network/sq/subquery/base-goerli-dictionary"

dataSources:
  - kind: ethereum/Runtime # We use ethereum runtime since Base is EVM-compatible
    startBlock: 3060969 # This is the block that the contract was deployed on https://goerli.basescan.org/tx/0x3901609b27f80e44b4530c4beaf8484635c088a8e24524e02d7b2571d4f40840
    options:
      # Must be a key of assets
      abi: erc20
      address: "0x2e9f75df8839ff192da27e977cd154fd1eae03cf" # This is the contract address for USDC https://goerli.basescan.org/token/0x2e9f75df8839ff192da27e977cd154fd1eae03cf
    assets:
      erc20:
        file: "./abis/erc20.abi.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleTransaction
          kind: ethereum/TransactionHandler # We use ethereum handlers since Base is EVM-compatible
          filter:
            ## The function can either be the function fragment or signature
            # function: '0x095ea7b3'
            # function: '0x7ff36ab500000000000000000000000000000000000000000000000000000000'
            function: approve(address spender, uint256 amount)
        - handler: handleLog
          kind: ethereum/LogHandler # We use ethereum handlers since Base is EVM-compatible
          filter:
            topics:
              ## Follows standard log filters https://docs.ethers.io/v5/concepts/events/
              - Transfer(address indexed from, address indexed to, uint256 amount)
              # address: "0x60781C2586D68229fde47564546784ab3fACA982"
