# NOTE THIS FILE IS HAS BEEN DEPRECATED AND REPLACED BY THE TYPESCRIPT DEFINITION (PROJECT.TS)
# The CLI will automatically look for the project.ts as priority, if you want to ensure you
# use the project manifest, please delete project.ts

specVersion: "1.0.0"

name: "arbitrum-nova-subql-starter"
version: "0.0.1"
runner:
  node:
    name: "@subql/node-ethereum"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: "This project can be use as a starting point for developing your new Arbitrum Nova SubQuery project"
repository: "https://github.com/subquery/ethereum-subql-starter"

schema:
  file: "./schema.graphql"

network:
  # chainId is the EVM Chain ID, for Arbitrum Nova this is 42170
  # https://chainlist.org/chain/42170
  chainId: "42170"
  # These endpoint(s) should be non-pruned archive nodes
  # We recommend providing more than Nova endpoint for improved reliability, performance, and uptime
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  # We suggest providing an array of endpoints for increased speed and reliability
  endpoint: ["https://nova.arbitrum.io/rpc"]
  # Recommended to provide the HTTP endpoint of a full chain dictionary to speed up processing
  # dictionary: "https://gx.api.subquery.network/sq/subquery/arbitrum-nova-dictionary" - we don't have one for Nova

dataSources:
  - kind: ethereum/Runtime # We use ethereum runtime since Arbitrum Nova is a layer-2 that is compatible
    startBlock: 15143 # This is the block that the contract was deployed on https://nova.arbiscan.io/tx/0x394b14597667a6104b54496bd35356cfcfec8e2e24bdc41886fb07f7d71fe2af
    options:
      # Must be a key of assets
      abi: erc20
      address: "0x765277EebeCA2e31912C9946eAe1021199B39C61" # This is the contract address for wrapped Eth https://nova.arbiscan.io/token/0x765277EebeCA2e31912C9946eAe1021199B39C61
    assets:
      erc20:
        file: "./abis/erc20.abi.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleTransaction
          kind: ethereum/TransactionHandler # We use ethereum handlers since Arbitrum Nova is a layer-2 that is compatible
          filter:
            ## The function can either be the function fragment or signature
            # function: '0x095ea7b3'
            # function: '0x7ff36ab500000000000000000000000000000000000000000000000000000000'
            function: approve(address spender, uint256 amount)
        - handler: handleLog
          kind: ethereum/LogHandler # We use ethereum handlers since Arbitrum Nova is a layer-2 that is compatible
          filter:
            topics:
              ## Follows standard log filters https://docs.ethers.io/v5/concepts/events/
              - Transfer(address indexed from, address indexed to, uint256 amount)
              # address: "0x60781C2586D68229fde47564546784ab3fACA982"
